-- SEED DATA FOR ALL 8 STATES AND CITIES
-- ASSAM
INSERT INTO cities (name, slug, state_id, description, budget_per_day, how_to_reach, seo_title, seo_description, last_verified_date) VALUES
('Guwahati', 'guwahati', (SELECT id FROM states WHERE name = 'Assam'), 'Gateway to the North East, famous for Kamakhya Temple and the mighty Brahmaputra river.', 1500, 'Guwahati International Airport, Guwahati Railway Station.', 'Guwahati Travel Guide | Plan Your Trip to Assam', 'Explore Guwahati, the hub of North East India. Discover top attractions, temples, and river cruises.', CURRENT_DATE),
('Kaziranga', 'kaziranga', (SELECT id FROM states WHERE name = 'Assam'), 'UNESCO World Heritage site home to the one-horned rhinoceros and diverse wildlife.', 2000, '5 hours drive from Guwahati airport or railway station.', 'Explore Kaziranga National Park | One-Horned Rhino Safari', 'Plan your wildlife adventure at Kaziranga. Best time to visit, safari timings, and stay guide.', CURRENT_DATE),
('Majuli Island', 'majuli-island', (SELECT id FROM states WHERE name = 'Assam'), 'Largest river island in the world and the cultural capital of Assam.', 1200, 'Ferry from Nimati Ghat near Jorhat.', 'Majuli Island Guide | World''s Largest River Island', 'Discover the unique Neo-Vaishnavite culture and satras of Majuli Island, Assam.', CURRENT_DATE),
('Tezpur', 'tezpur', (SELECT id FROM states WHERE name = 'Assam'), 'The City of Eternal Romance with a deep-rooted history in mythology.', 1000, '3.5 hours drive from Guwahati.', 'Tezpur Travel Guide | The Cultural Capital of Assam', 'Explore the historical monuments and scenic beauty of Tezpur, Assam.', CURRENT_DATE),
('Haflong', 'haflong', (SELECT id FROM states WHERE name = 'Assam'), 'The only hill station in Assam, known for its scenic views and diverse tribes.', 1000, 'Haflong Railway Station (well connected via Vistadome).', 'Haflong Hill Station Guide | Secret Gem of Assam', 'Discover the breathtaking hills and lakes of Haflong, the only hill station in Assam.', CURRENT_DATE),
('Sivasagar', 'sivasagar', (SELECT id FROM states WHERE name = 'Assam'), 'The historical seat of the Ahom Kingdom with majestic temples and palaces.', 900, 'Night bus or train from Guwahati to Sivasagar station.', 'Sivasagar Historical Guide | Ahom Kingdom Heritage', 'Visit the ancient capital of the Ahom dynasty. Explore Shiva Dol and Rang Ghar.', CURRENT_DATE);

-- ARUNACHAL PRADESH
INSERT INTO cities (name, slug, state_id, description, budget_per_day, how_to_reach, seo_title, seo_description, last_verified_date) VALUES
('Tawang', 'tawang', (SELECT id FROM states WHERE name = 'Arunachal Pradesh'), 'High-altitude town known for its massive monastery and breathtaking Sela Pass.', 2500, 'Shared taxi or private car from Guwahati/Tezpur (12-14 hours).', 'Tawang Travel Guide | Monastery and Mountains', 'Explore Tawang: Land of the Monpa people, ancient monasteries, and serene lakes.', CURRENT_DATE),
('Ziro Valley', 'ziro-valley', (SELECT id FROM states WHERE name = 'Arunachal Pradesh'), 'A picturesque valley home to the Apatani tribe and the famous Ziro Music Festival.', 1500, 'Train to Naharlagun, then 4 hours drive.', 'Ziro Valley Guide | Home of the Apatani Tribe', 'Visit Ziro for its unique culture, lush green valleys, and world-class music festival.', CURRENT_DATE),
('Bomdila', 'bomdila', (SELECT id FROM states WHERE name = 'Arunachal Pradesh'), 'A serene town offering panoramic views of the Himalayas and ancient monasteries.', 1500, '8 hours drive from Guwahati.', 'Bomdila Travel Guide | Gateway to Tawang', 'Plan your stay in Bomdila. Discover viewpoints, monasteries, and apple orchards.', CURRENT_DATE),
('Dirang', 'dirang', (SELECT id FROM states WHERE name = 'Arunachal Pradesh'), 'A beautiful valley known for its hot springs, apple orchards, and old fort (Dzong).', 1200, '7 hours drive from Guwahati.', 'Dirang Valley Guide | Hot Springs and Orchards', 'Explore Dirang, a peaceful stopover on the way to Tawang with unique culture.', CURRENT_DATE),
('Pasighat', 'pasighat', (SELECT id FROM states WHERE name = 'Arunachal Pradesh'), 'The oldest town in Arunachal, situated on the banks of the Siang River.', 1500, 'Bus or taxi from Itanagar or Dibrugarh via ferry.', 'Pasighat Guide | The Gateway of Arunachal', 'Discover Pasighat, the oldest town on the Siang river bank. Best for rafting.', CURRENT_DATE),
('Itanagar', 'itanagar', (SELECT id FROM states WHERE name = 'Arunachal Pradesh'), 'The capital city known for the Ita Fort and the Gekar Sinyi (Ganga Lake).', 1500, 'Flight to Hollongi Airport or train to Naharlagun.', 'Itanagar Capital Guide | History and Nature', 'Visit the capital of Arunachal Pradesh. Explore Ita Fort and Buddhist monasteries.', CURRENT_DATE);

-- NAGALAND
INSERT INTO cities (name, slug, state_id, description, budget_per_day, how_to_reach, seo_title, seo_description, last_verified_date) VALUES
('Kohima', 'kohima', (SELECT id FROM states WHERE name = 'Nagaland'), 'Hill capital town, famous for the Hornbill Festival and World War II history.', 1500, '2.5 hours drive from Dimapur railway station.', 'Kohima Travel Guide | Hornbill Festival Capital', 'Explore Kohima: History of the Nagas, WWII Cemetery, and the famous festivals.', CURRENT_DATE),
('Dimapur', 'dimapur', (SELECT id FROM states WHERE name = 'Nagaland'), 'The commercial hub and entry point of Nagaland, home to Kachari ruins.', 1200, 'Well connected by air and rail to Guwahati and Kolkata.', 'Dimapur Travel Guide | Gateway to Nagaland', 'Discover Dimapur heritage, its ancient Kachari ruins, and bustling markets.', CURRENT_DATE),
('Mon', 'mon', (SELECT id FROM states WHERE name = 'Nagaland'), 'Home of the Konyak Nagas, famous for their facial tattoos and wood carvings.', 1500, 'Bus or taxi from Dibrugarh or Jorhat (Assam).', 'Mon Nagaland Guide | Konyak Tribe Heritage', 'Visit the land of the Konyaks. Explore tribal heritage, tattoos, and longhouses.', CURRENT_DATE),
('Mokokchung', 'mokokchung', (SELECT id FROM states WHERE name = 'Nagaland'), 'Cultural center of the Ao Nagas, known for its vibrant festivals and traditions.', 1200, '6 hours drive from Jorhat, Assam.', 'Mokokchung Guide | Ao Naga Cultural Center', 'Explore Mokokchung: the pulse of Ao Naga traditions and beautiful hill scenery.', CURRENT_DATE);

-- SIKKIM
INSERT INTO cities (name, slug, state_id, description, budget_per_day, how_to_reach, seo_title, seo_description, last_verified_date) VALUES
('Gangtok', 'gangtok', (SELECT id FROM states WHERE name = 'Sikkim'), 'The vibrant capital known for its MG Road, monasteries, and views of Kanchenjunga.', 2000, '4 hours drive from Bagdogra airport or NJP station.', 'Gangtok Travel Guide | Explore the Capital of Sikkim', 'Discover Gangtok: monasteries, cable cars, and the best views of the Himalayas.', CURRENT_DATE),
('Pelling', 'pelling', (SELECT id FROM states WHERE name = 'Sikkim'), 'A peaceful town offering the closest views of Mount Kanchenjunga.', 1800, '5 hours drive from Gangtok or Siliguri.', 'Pelling Travel Guide | Closest Kanchenjunga Views', 'Visit Pelling for its Skywalk, ancient monasteries, and lush waterfalls.', CURRENT_DATE),
('Lachung', 'lachung', (SELECT id FROM states WHERE name = 'Sikkim'), 'A high-altitude village that serves as the gateway to Yumthang Valley.', 2500, '6 hours drive from Gangtok.', 'Lachung Travel Guide | Gateway to Yumthang Valley', 'Explore North Sikkim from Lachung. Tips for visiting Yumthang and Zero Point.', CURRENT_DATE),
('Lachen', 'lachen', (SELECT id FROM states WHERE name = 'Sikkim'), 'Base for Gurudongmar Lake, one of the highest and most sacred lakes.', 2500, '6 hours drive from Gangtok.', 'Lachen Travel Guide | Base for Gurudongmar Lake', 'Plan your visit to North Sikkim from Lachen. Permits and logistics guide.', CURRENT_DATE),
('Namchi', 'namchi', (SELECT id FROM states WHERE name = 'Sikkim'), 'The religious hub of Sikkim, famous for the Samdruptse Hill and Char Dham.', 1500, '3 hours drive from Gangtok.', 'Namchi South Sikkim Guide | Religious and Scenic', 'Discover the massive statues and spiritual legacy of Namchi, South Sikkim.', CURRENT_DATE),
('Yuksom', 'yuksom', (SELECT id FROM states WHERE name = 'Sikkim'), 'The first capital of Sikkim and the base for the Goechala Trek.', 1500, '5 hours drive from Siliguri.', 'Yuksom Guide | Gateway to Kanchenjunga National Park', 'Visit the historic first capital. Base for Sikkim''s best trekking routes.', CURRENT_DATE);

-- MANIPUR
INSERT INTO cities (name, slug, state_id, description, budget_per_day, how_to_reach, seo_title, seo_description, last_verified_date) VALUES
('Imphal', 'imphal', (SELECT id FROM states WHERE name = 'Manipur'), 'Capital city rich in culture, historical ruins, and the unique Ima Market.', 1200, 'Well connected by air to Guwahati, Kolkata, and Delhi.', 'Imphal Travel Guide | Culture and History of Manipur', 'Explore the capital of Manipur. Visit Kangla Fort and the women''s market.', CURRENT_DATE),
('Loktak Lake', 'loktak-lake', (SELECT id FROM states WHERE name = 'Manipur'), 'The largest freshwater lake in NE India, famous for its floating Phumdis.', 1000, '1.5 hours drive from Imphal.', 'Loktak Lake Guide | World''s only Floating National Park', 'Discover the unique ecosystem of Loktak Lake and Keibul Lamjao Park.', CURRENT_DATE),
('Ukhrul', 'ukhrul', (SELECT id FROM states WHERE name = 'Manipur'), 'Known for its scenic hills and the rare Shirui Lily.', 1200, '3 hours drive from Imphal.', 'Ukhrul Travel Guide | Scenic Hills and Shirui Lily', 'Visit Ukhrul for its breathtaking landscapes and unique flora and fauna.', CURRENT_DATE);

-- MIZORAM
INSERT INTO cities (name, slug, state_id, description, budget_per_day, how_to_reach, seo_title, seo_description, last_verified_date) VALUES
('Aizawl', 'aizawl', (SELECT id FROM states WHERE name = 'Mizoram'), 'A steep hill city with a relaxed vibe and beautiful surrounding peaks.', 1500, 'Connected by air via Lengpui airport from Kolkata/Guwahati.', 'Aizawl Travel Guide | The Pulse of Mizoram', 'Discover Aizawl: The capital city of Mizoram, culture, and viewpoints.', CURRENT_DATE),
('Reiek', 'reiek', (SELECT id FROM states WHERE name = 'Mizoram'), 'Famous for its Tlang/Peak offering views of the surrounding plains of Tripura.', 1000, '1 hour drive from Aizawl.', 'Reiek Tlang Guide | Beautiful Mizoram Viewpoints', 'Climb Reiek Peak for spectacular views. Explore the heritage village.', CURRENT_DATE);

-- TRIPURA
INSERT INTO cities (name, slug, state_id, description, budget_per_day, how_to_reach, seo_title, seo_description, last_verified_date) VALUES
('Agartala', 'agartala', (SELECT id FROM states WHERE name = 'Tripura'), 'Capital city known for the white Ujjayanta Palace and royal history.', 1200, 'Well connected by air and rail to main Indian cities.', 'Agartala Travel Guide | Royal Heritage of Tripura', 'Explore Agartala: Palaces, temples, and the vibrant culture of Tripura.', CURRENT_DATE),
('Unakoti', 'unakoti', (SELECT id FROM states WHERE name = 'Tripura'), 'The Angkor Wat of the North East, famous for massive rock-cut carvings.', 900, 'Train to Dharmanagar, then 45 mins drive.', 'Unakoti Rock Carvings Guide | Ancient Heritage', 'Discover the mysterious and massive rock carvings of Unakoti, Tripura.', CURRENT_DATE);
